# .circleci/config.yml
#
# This file configures the CircleCI 2.0 build.
#
# Documentation:
# - Overview: https://circleci.com/docs/2.0/workflows/
# - Caching: https://circleci.com/docs/2.0/caching/
#
# Things to know:
# - every job is a container
# - cache is used for data that can potentially be reused between builds, provided we can
#   be sure it will not influence the build result other than by speeding it up.
# - cache is immutable. Sometimes we need to flush the cache, but we can't. That's why there is this
#   `v1-` at the beginning. Increment it when you need to change the cache content.
# - because we use `npm ci`, we cache the `~/.npm` directory and not `node_modules` which
#   is erased by `npm ci`.
# - to make sure the cache is indexed by the `package.json` and `package-lock.json` files,
#   we concatenate them into a temporary file whose checksum we use as part of the cache key.
# - for data that is specific to a build (commit), like the source code downloaded from github,
#   we use Circle CI's workspace feature to transport it between jobs.

version: 2.1

commands:
  npm_ci:
    description: "Run 'npm ci' with cache"
    parameters:
      cache_key:
        type: string
    steps:
      - run: cat package*.json > cachekey
      - restore_cache:
          key: v7-<< parameters.cache_key >>-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - save_cache:
          key: v7-<< parameters.cache_key >>-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - checkout:
          filters:
            branches:
              ignore:
                - master
                - math
                - preview
                - gh-pages
                - /release-.*/

      - api_build_and_test:
          requires:
            - checkout

      - ember_build:
          name: mon-pix_build_and_test
          directory: mon-pix
          parallelism: 3
          requires:
            - checkout

      - ember_build:
          name: orga_build_and_test
          directory: orga
          requires:
            - checkout

      - ember_build:
          name: certif_build_and_test
          directory: certif
          requires:
            - checkout

      - ember_build:
          name: admin_build_and_test
          directory: admin
          requires:
            - checkout

      - signal_ci_ok:
          requires:
            - api_build_and_test
            - mon-pix_build_and_test
            - orga_build_and_test
            - certif_build_and_test
            - admin_build_and_test
          filters:
            branches:
              ignore:
                - dev

jobs:
  checkout:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/pix
    steps:
      - checkout
      - run: rm -rf .git/
      - persist_to_workspace:
          root: ~/pix
          paths:
            - .

  api_build_and_test:
    docker:
      - image: circleci/node:10.15
      - image: postgres:10-alpine
        environment:
          POSTGRES_USER: circleci
    working_directory: ~/pix/api
    steps:
      - attach_workspace:
          at: ~/pix
      - npm_ci:
          cache_key: api
      - run: |
          npm run lint
          npm test
      - run:
          command: |
            npm run db:migrate
            npm run db:seed
          environment:
            TEST_DATABASE_URL: postgres://circleci@localhost:5432/circleci
            NODE_ENV: test

  ember_build:
    parameters:
      directory:
        type: string
      parallelism:
        type: integer
        default: 1
    docker:
      - image: circleci/node:10.15-browsers
        environment:
          # See https://git.io/vdao3 for details.
          JOBS: 2
    working_directory: ~/pix/<< parameters.directory >>
    parallelism: << parameters.parallelism >>
    steps:
      - attach_workspace:
          at: ~/pix
      - npm_ci:
          cache_key: << parameters.directory >>
      - run: npm test
      - store_test_results:
          path: test-results

  signal_ci_ok:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/pix
    steps:
      - attach_workspace:
          at: ~/pix
      - npm_ci:
          cache_key: root
      - run: sudo apt-get install -y jq
      - run: npm run ci:signal-jira
      - run: ~/pix/scripts/signal_deploy_to_pr.sh
